INSERT INTO USER_DETAILS (USERNAME,CREATED_DATE,UPDATED_DATE) VALUES('POOL ACCOUNT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO USER_ACCOUNTDETAILS(USERID,ACCOUNT_NUMBER,BALANCE,EARMARKAMOUNT,LOANAMOUNT,ISLOANPAYMNETALLOWED,VERSION,CREATED_DATE,UPDATED_DATE) VALUES (1,'POOL ACCOUNT',100000,0,0,'TRUE',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
