INSERT INTO USER_DETAILS (USERNAME,CREATED_DATE,UPDATED_DATE) VALUES('POOL ACCOUNT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO USER_ACCOUNTDETAILS(USERID,ACCOUNT_NUMBER,BALANCE,EARMARKAMOUNT,LOANAMOUNT,VERSION,CREATED_DATE,UPDATED_DATE) VALUES (1,'123123',100000,0,0,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO USER_TRANSACTIONS(DEBIT_USERID,DEBIT_ACCOUNT_ID,CREDIT_USERID,CREDIT_ACCOUNT_ID,TRANSACTION_AMOUNT,TRANSACTION_TYPE,CREATED_DATE,UPDATED_DATE) VALUES(1,'123',2,'345',10,'TOPUP',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);