INSERT INTO USER_DETAILS (USERNAME,CREATED_DATE,UPDATED_DATE) VALUES('POOL ACCOUNT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO USER_ACCOUNTDETAILS(USERID,ACCOUNT_NUMBER,BALANCE,EARMARKAMOUNT,VERSION,CREATED_DATE,UPDATED_DATE) VALUES (1,'POOL ACCOUNT',100000,0,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO USER_LOANDETAILS(USERID,ACCOUNT_NUMBER,BALANCE,EARMARKAMOUNT,PAY_TO_USERID,VERSION,CREATED_DATE,UPDATED_DATE) VALUES (1,'TEST LOAN ACCOUNT',100000,0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

