DROP TABLE IF EXISTS USER_DETAILS;
CREATE TABLE USER_DETAILS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(255) NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP(),
UNIQUE (USERNAME)
);


DROP TABLE IF EXISTS USER_ACCOUNTDETAILS;
CREATE TABLE USER_ACCOUNTDETAILS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERID INT NOT NULL,
ACCOUNT_NUMBER VARCHAR(40) NOT NULL,
BALANCE DOUBLE NOT NULL,
EARMARKAMOUNT DOUBLE,
VERSION INT NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP(),
UNIQUE (USERID)
);

DROP TABLE IF EXISTS USER_LOANDETAILS;
CREATE TABLE USER_LOANDETAILS (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USERID INT NOT NULL,
  ACCOUNT_NUMBER VARCHAR(40) NOT NULL,
  BALANCE DOUBLE NOT NULL,
  EARMARKAMOUNT DOUBLE,
  PAY_TO_USERID INT NOT NULL,
  VERSION INT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
UPDATED_DATE TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP(),
UNIQUE (USERID)
);


DROP TABLE IF EXISTS USER_TRANSACTIONS;
CREATE TABLE USER_TRANSACTIONS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DEBIT_USERID INT NOT NULL,
DEBIT_ACCOUNT_ID VARCHAR(40) NOT NULL,
CREDIT_USERID  INT NOT NULL,
CREDIT_ACCOUNT_ID VARCHAR(40) NOT NULL,
TRANSACTION_AMOUNT DOUBLE NOT NULL,
TRANSACTION_TYPE VARCHAR(40) NOT NULL,
CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
UPDATED_DATE TIMESTAMP NOT NULL DEFAULT  '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP()
);