package com.clibank.clibank.constants;

public enum PaymentTransactionTypes {
        PAYMENT_TRANCTION_SUCESS("000"),
        LOAN_TRANSACTION_SUCCESS("007"),
        INVALID_PAYMENT_TRANSACTION_NO_DEBIT_BALANCE("011"),
    INVALID_PAYMENT_TRANSACTION_NO_LOAN_ALLOWED_EXISTING_LOAN_PRESENT("011"),
    PAYMNET_AND_LOAN_SUCCESS("012"),
    TOP_UP_FAILURE("014"),
    TOP_UP_SUCCESS("015"),
    TOP_UP_SUCCESS_LOANPAYMENT_SUCCESS("015"),
    TOP_UP_SUCCESS_LOANPAYMENT_SUCCESS_UPDATE_LOAN_AMOUNT_FAILURE("016"),
    TOP_UP_SUCCESS_LOAN_REPAYMENT_FAILURE("017"),
    PAYMENT_TO_LOAN_SUCCESS("018"),
    DEBIT_SUCCESS_CREDIT_SUCCESS_TRNRECORD_CREATE_SUCCESS_REMOVE_DEBIT_EAR_MARK_FAIURE_TRAN_SUCCESS("026"),
    LOAN_REPAY_DISPUTE_PRENDING("027"),
    PAYMENT_INITIATED_WITH_LOAN_AND_PAYMENT_SUCCESS_LOAN_FAILURE("029"),
    LOAN_ACCOUNT_CREATION_FAILURE("033"),
    PAYMENT_TRANCTION_FAILURE("034"),
    PAYMENT_TO_LOAN_FAILURE("035"),
    NO_LOAN_ASSOCIATED("036"),
    LOAN_TRAN_FAILURE("036"),
    PAYMENT_TO_LOAN_ONLY_SUCCESS("037");



private String code;

    private PaymentTransactionTypes(String code){
            this.code = code;
    }

    public String value(){
            return  this.code;
    }


}
