package com.clibank.clibank.constants;

public enum UserCreation {
    USER_CREATION_FAILURE,
    USER_CREATION_SUCCESS_ACCOUNT_CREATION_FAILURE,
    USER_ACCOUNT_CREATION_EXCEPTION,
    USER_ACCOUNT_CREATION_SUCCESS,
    USER_EXIST_IN_SYSTEM;

}
